import 'package:flutter/material.dart';

class strings {
  static final String prepaid ="My Prepaid";
  static final String load ="Load Balance";
  static final String value ="P 1675.00";
  static final String validity =" Valid till 26 Dec";
  static final String databalance ="Data Balance";
  static final String data = "300MB";
  static final String recommended ="Recommended";
  static final String viewall ="View all";
  static final String go350 = "GoUNLI350";
  static final String days = "30 days UNLI to Globe ";
  static final String go180 = "GoUNLI180";
  static final String days15 = " 15 days UNLI to Globe";
  static final String special = "Special Promos";
  static final String gosakto ="GoSakto";
  static final String totaldata ="of 12GB";
  static String createwhat ="Create What Matters";
  static String promo ="Promo that's all you";
  static String createpromo = "Create your own Promo";
  static String spotify = "Spotify Premium";
  static String subscribe ="Subscribe for";
  static String cost ="P 129.00/m";
  static String latest = "Latest Promos";
  static String facebook ="Facebook Surf";
  static String pack = "Get pack for";
  static String fcost ="P 50.00/m";
  static String roaming = "Roaming Plans";
  static String plan = "Planning for a foreign trip?";
  static String roam = "Roam worry free!";
  static String explore = "Explore Roaming Packs";
  static String globerewards = "Globe Rewards";
  static String  rewards = "YOUR REWARD POINTS";
  static String points = "7250 Pts";
  static String offers = "Here is what you can get";
  static String pts = "1000 Pts";
  static String off = "P 500 OFF on Shoes";
  static String hairspa = "Get Hair Spa & Styling";
  static String findout ="Find Out More";
  static String subscription = "My Subscriptions";
  static String watchvideo = "With remaining 12GB, you can watch 640 min of video";
  static String popular = "Popular on";
  static String prime = "Latest on";
  static String mightlike = "You might also like";
  static String haq ="Subscribe for";
  static String haqcost = "P 129.00/m";
  static String NEW = "NEW";

}